server:
  port: 8080

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://host.docker.internal:3309/store?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  application:
    name: order-service
# Feign Client 설정
member:
  service:
    url: http://member-service:8080

product:
  service:
    url: http://product-service:8080

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  httpclient:
    enabled: true  # Apache HttpClient 활성화

# 로깅 설정
logging:
  level:
    com.msa.order: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cloud.openfeign: DEBUG

# JWT 설정
jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  tokenValidityInMilliseconds: 86400000

# Actuator 설정 - Redis Health Check 비활성화
management:
  health:
    redis:
      enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka
---
# Docker 환경 설정
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/store?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

member:
  service:
    url: http://member-service:8080
