apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: ecommerce
  labels:
    app: gateway-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: teachd/gateway-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: application-config
              key: EUREKA_SERVER_URL
#        resources:
#          requests:
#            memory: "512Mi"
#            cpu: "250m"
#          limits:
#            memory: "1Gi"
#            cpu: "500m"
#        livenessProbe:
#          httpGet:
#            path: /actuator/health/liveness
#            port: 8000
#          initialDelaySeconds: 60
#          periodSeconds: 10
#        readinessProbe:
#          httpGet:
#            path: /actuator/health/readiness
#            port: 8000
#          initialDelaySeconds: 30
#          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: ecommerce
  labels:
    app: gateway-service
spec:
  type: LoadBalancer  # AWS ELB 생성
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: gateway-service